version: '3.8'
services:
    mysql:
        container_name: test-mysql
        image: mysql:8.0.36
        restart: always
        ports:
            - ${DB_PORT}:${DB_PORT}
        environment:
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        volumes:
            - test-mysql:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u$$DB_USER", "-p$$DB_PASSWORD"]
            interval: 5s
            timeout: 20s
            retries: 30
    php:
        container_name: test-php
        build:
            context: docker
            dockerfile: php/DockerFile
        depends_on:
            mysql:
                condition: service_healthy
        working_dir: /home
        volumes:
            - ./test:/home
        env_file:
            - .env
volumes:
    test-mysql:
    test-php:
